language: shell
sudo: required
dist: xenial
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.deb
  - sudo dpkg -i hugo*_Linux-64bit.deb
  - hugo version
  - rm hugo*_Linux-64bit.deb
script:
  - hugo
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: false
  local_dir: public
  repo: MrinalJain17/MrinalJain17.github.io
  target_branch: master
  on:
    branch: master
